// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeH-7S-dvAsCVpnL5gZzTOEPt3FOAQwf4',
    appId: '1:1013592627103:web:d56fe63b5cf2969e0e8faa',
    messagingSenderId: '1013592627103',
    projectId: 'kaybul',
    authDomain: 'kaybul.firebaseapp.com',
    storageBucket: 'kaybul.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACbIzPlHO0pGioNkmyuQa1BlI0zlLUvZU',
    appId: '1:1013592627103:android:283229a1531bb70e0e8faa',
    messagingSenderId: '1013592627103',
    projectId: 'kaybul',
    storageBucket: 'kaybul.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChZ3zM90TJDAIqHOOyHCZQwZpfwUe2bdE',
    appId: '1:1013592627103:ios:56eea4587ffa2b430e8faa',
    messagingSenderId: '1013592627103',
    projectId: 'kaybul',
    storageBucket: 'kaybul.appspot.com',
    iosBundleId: 'com.example.kaybulApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChZ3zM90TJDAIqHOOyHCZQwZpfwUe2bdE',
    appId: '1:1013592627103:ios:7bccee3c6fb0f6c30e8faa',
    messagingSenderId: '1013592627103',
    projectId: 'kaybul',
    storageBucket: 'kaybul.appspot.com',
    iosBundleId: 'com.example.kaybulApp.RunnerTests',
  );
}
